# Список книг
GET http://localhost:3000/api/books HTTP/1.1

###

# Просмотр информации о первой книге
GET http://localhost:3000/api/books/2 HTTP/1.1

###

# Добавление новой книги
POST http://localhost:3000/api/books HTTP/1.1
Content-Type: "application/json"

{
  "title": "The Dead Zone",
}

###

# Несуществующий маршрут
GET http://localhost:3000/bad-route HTTP/1.1
